# -*- coding: utf-8 -*-
"""rag_chatbot

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PCxk7B7Qwd3f3Ch6yzvg4ERdSbuCSVez
"""

!pip install --upgrade langchain langchain-core langchain-groq

import os
os.environ["GROQ_API_KEY"]="GROQ_API_KEY"

os.environ["LANGCHAIN_TRACING_V2"] = "true"
os.environ["LANGSMITH_API_KEY"] = "LANGSMITH_API_KEY"
os.environ["LANGCHAIN_PROJECT"] = "langchain-course"

from langchain_groq import ChatGroq  # pip install langchain-groq

llm = ChatGroq(model="llama-3.3-70b-versatile", groq_api_key="GROQ_API_KEY", temperature=0)
llm_response = llm.invoke("Tell me a joke")
print(llm_response.content)

from langchain_core.output_parsers import StrOutputParser

output_parser = StrOutputParser()
output_parser.invoke(llm_response)

chain = llm | output_parser
chain.invoke("Tell me a joke")

"""Structured Output"""

from typing import List
from pydantic import BaseModel, Field

class MobileReview(BaseModel):
        phone_model: str = Field(description="Name and model of the phone")
        rating: float = Field(description="Overall rating out of 5")
        pros: List[str] = Field(description="List of positive aspects")
        cons: List[str] = Field(description="List of negative aspects")
        summary: str = Field(description="Brief summary of the review")
review_text = """
    Just got my hands on the new Galaxy S21 and wow, this thing is slick! The screen is gorgeous,
    colors pop like crazy. Camera's insane too, especially at night - my Insta game's never been
    stronger. Battery life's solid, lasts me all day no problem.
    Not gonna lie though, it's pretty pricey. And what's with ditching the charger? C'mon Samsung.
    Also, still getting used to the new button layout, keep hitting Bixby by mistake.
    Overall, I'd say it's a solid 4 out of 5. Great phone, but a few annoying quirks keep it from
    being perfect. If you're due for an upgrade, definitely worth checking out!
    """
structured_llm = llm.with_structured_output(MobileReview)
output = structured_llm.invoke(review_text)
print(output)
print(output.pros)

"""Prompt Template

"""

from langchain_core.prompts import ChatPromptTemplate
prompt = ChatPromptTemplate.from_template("Tell me a short joke about {topic}")
prompt.invoke({"topic": "programming"})

chain = prompt | llm | output_parser
chain.invoke({"topic": "car drivers"})

from langchain_groq import ChatGroq
from langchain_core.prompts import ChatPromptTemplate
from langchain_core.output_parsers import StrOutputParser

#Define the prompt
prompt = ChatPromptTemplate.from_template("Tell me a short joke about {topic}")

#Initialize the llm
llm = ChatGroq(model="llama-3.3-70b-versatile")

#define the output parser
output_parser = StrOutputParser()

#Compose the chain
chain = prompt | llm | output_parser

#use the chain
result = chain.invoke({"topic": "programming"})
print(result)

"""LLM Messages"""

from langchain_core.output_parsers import StrOutputParser
from langchain_core.messages import HumanMessage, SystemMessage

system_message = SystemMessage(content="you are a helpful assistant that tells jokes.")
human_message = HumanMessage(content="Tell me about programming")
llm.invoke([system_message, human_message])

from langchain_core.prompts import ChatPromptTemplate
from langchain_core.messages import SystemMessage, HumanMessage, AIMessage

# Corrected: Use ChatPromptTemplate.from_messages for a list of message tuples
template = ChatPromptTemplate([
    ("system", "You are a helpful assistant that codes efficiently."),
    ("human","Tell me about {topic}")
])

prompt_value = template.invoke({
    "topic": "programming"
})
prompt_value

llm.invoke(prompt_value)

!pip install pypdf
!pip install -U langchain-community
from langchain_community.document_loaders import PyPDFLoader, Docx2txtLoader, UnstructuredPDFLoader, PDFMinerLoader, PyMuPDFLoader, UnstructuredWordDocumentLoader
from langchain_text_splitters import RecursiveCharacterTextSplitter
from langchain_community.embeddings import HuggingFaceEmbeddings
from typing import List
from langchain_core.documents import Document

text_splitter = RecursiveCharacterTextSplitter(
                chunk_size=1000,
                chunk_overlap=200,
                length_function=len
)
docx_loader = PyPDFLoader("/content/docs/@bhishek_cv.pdf")
documents = docx_loader.load()

print(len(documents))

splits = text_splitter.split_documents(documents)

print(f"Split the documents into {len(splits)} chunks")

documents[0]

splits[0]

splits[0].metadata

splits[0].page_content

#1. function to load documents from a folder

def load_documents(folder_path: str) -> List[Document]:
  documents = []
  for filename in os.listdir(folder_path):
    file_path = os.path.join(folder_path, filename)
    if filename.endswith(".pdf"):
      loader = PyPDFLoader(file_path)
    elif filename.endswith(".docx"):
      loader = Docx2txtLoader(file_path)
    else:
      print(f"Unsupported file type: {filename}")
      continue
    documents.extend(loader.load())
    return documents

# Load documents from a folder
folder_path = "/content/docs"
documents = load_documents(folder_path)

print(f"Loaded {len(documents)} documents from the folder")
split = text_splitter.split_documents(documents)
print(f"Split the documents into {len(splits)} chunks")

embeddings = HuggingFaceEmbeddings()

#4. Embedding Documents

document_embeddings = embeddings.embed_documents([split.page_content for split in splits])

print(f"Created embeddings for {len(document_embeddings)} document chunks")

document_embeddings[0]

!pip install -U langchain-chroma chromadb
from langchain_chroma import Chroma

embedding_function = HuggingFaceEmbeddings()
collection_name = "my_collection"
vectorstore = Chroma.from_documents(collection_name=collection_name, documents=splits, embedding=embedding_function)

print("Vector store created and persisted to'./chroma_db")

#5 perform similarity search

query = "what are the skills abhishek have?"
search_results = vectorstore.similarity_search(query, k=2)

print(f"\nTop 2 most relevant chunks for the query: {query}'\n'")
for i, result in enumerate(search_results, 1):
  print(f"Result {i}:")
  print(f"Source: {result.metadata.get('source', 'Unknown')}")
  print(f"Content: {result.page_content}")
  print()

retriever = vectorstore.as_retriever(search_kwargs={"k": 2})
retriever.invoke("what are the skills abhishek have?")

from langchain_core.prompts import ChatPromptTemplate
template = """Answer the question based only on the following context:
{context}

Question:{question}

Answer: """
prompt = ChatPromptTemplate.from_template(template)

from langchain_core.runnables import RunnablePassthrough

# build the RAG runnable (assumes retriever and prompt already exist)
rag_chain = ({"context": retriever, "question": RunnablePassthrough()} | prompt)

# run it (keeps your original call)
rag_chain.invoke("what are the skills abhishek have?")

def docs2str(docs):
  return "\n\n".join(doc.page_content for doc in docs)

rag_chain = ({"context": retriever | docs2str, "question": RunnablePassthrough()} | prompt)
rag_chain.invoke("what skills abhishek have ?")

rag_chain = (
    {"context": retriever | docs2str, "question": RunnablePassthrough()}| prompt | llm | StrOutputParser()
)
question = "what are the skills abhishek have"
response = rag_chain.invoke(question)
print(response)

1 # Example conversation
from langchain_core.messages import HumanMessage, AIMessage
chat_history = []
chat_history.extend([HumanMessage(content=question),
                     AIMessage(content=response)])

chat_history

from langchain_core.prompts import ChatPromptTemplate, MessagesPlaceholder
from langchain_core.output_parsers import StrOutputParser

chat_history = []

contextualize_q_system_prompt = (
    "Given a chat history and the latest user question "
    "which might reference context in the chat history, "
    "formulate a standalone question which can be understood "
    "without the chat history. Do NOT answer the question, "
    "just reformulate it if needed and otherwise return it as is"
)

contextualize_q_prompt = ChatPromptTemplate.from_messages([
    ("system", contextualize_q_system_prompt),
    MessagesPlaceholder("chat_history"),
    ("human", "{input}")
])

contextualize_chain = contextualize_q_prompt | llm | StrOutputParser()

contextualize_chain.invoke({
    "input": "what mathematical subjects abhishek know",
    "chat_history": chat_history
})

!pip install --upgrade langchain langchain-community langchain-core
from langchain_classic.chains import create_history_aware_retriever
history_aware_retriever = create_history_aware_retriever(
    llm, retriever, contextualize_q_prompt
)
history_aware_retriever.invoke({"input":"what mathematical subjects abhishek know ?", "chat_history": chat_history})

!pip install -U langchain langchain-core langchain-community

!pip install langchain-classic
from langchain_classic.chains import create_retrieval_chain
from langchain_classic.chains.combine_documents import create_stuff_documents_chain

qa_prompt = ChatPromptTemplate.from_messages([
    ("system","You are a helpful AI assistant. Use the following context to answer the user's question."),
    ("system","Context: {context}"),
    MessagesPlaceholder(variable_name="chat_history"),
    ("human", "{input}"),
])

question_answer_chain = create_stuff_documents_chain(llm, qa_prompt)

rag_chain = create_retrieval_chain(history_aware_retriever, question_answer_chain)

"""Building Multi User Chatbot"""

import sqlite3
from datetime import datetime

DB_NAME = "rag_app.db"

def get_db_connection():
    conn = sqlite3.connect(DB_NAME)
    conn.row_factory = sqlite3.Row
    return conn

def create_application_logs():
    conn = get_db_connection()
    conn.execute('''CREATE TABLE IF NOT EXISTS application_logs
                    (id INTEGER PRIMARY KEY AUTOINCREMENT,
                     session_id TEXT,
                     user_query TEXT,
                     gpt_response TEXT,
                     model TEXT,
                     created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP)''')  # ✅ Fix 1 & 2
    conn.commit()  # ✅ Fix 3 - added commit
    conn.close()

def insert_application_logs(session_id, user_query, gpt_response, model):
    conn = get_db_connection()
    conn.execute('INSERT INTO application_logs (session_id, user_query, gpt_response, model) VALUES (?, ?, ?, ?)',  # ✅ Fix 4
                (session_id, user_query, gpt_response, model))
    conn.commit()
    conn.close()

def get_chat_history(session_id):
    conn = get_db_connection()
    cursor = conn.cursor()
    cursor.execute('SELECT user_query, gpt_response FROM application_logs WHERE session_id = ? ORDER BY created_at',
                   (session_id,))  # ✅ Fix 5 - separated properly
    messages = []
    for row in cursor.fetchall():
        messages.extend([
            {"role": "human", "content": row['user_query']},
            {"role": "ai", "content": row['gpt_response']}
        ])
    conn.close()
    return messages  # ✅ Fix 6 - moved outside loop

create_application_logs()

import uuid
session_id = str(uuid.uuid4())
chat_history = get_chat_history(session_id)
print(chat_history)
question1 = "what mathematical skills abhishek have ?"
answer1 = rag_chain.invoke({"input": question1, "chat_history":chat_history})['answer']
insert_application_logs(session_id, question1, answer1, "llama-3.3-70b-versatile")
print(f"Human: {question1}")
print(f"AI: {answer1}\n")

question2 = "what are the mathematical skills abhishek have ?"
chat_history = get_chat_history(session_id)
print(chat_history)
answer2 = rag_chain.invoke({"input": question2, "chat_history":chat_history})['answer']
insert_application_logs(session_id, question2, answer2, "llama-3.3-70b-versatile")
print(f"Human: {question2}")
print(f"AI: {answer2}\n")

"""New User

"""

session_id = str(uuid.uuid4())
question = "who is abhishek ?"
chat_history = get_chat_history(session_id)
print(chat_history)
answer = rag_chain.invoke({"input": question, "chat_history":chat_history})['answer']
insert_application_logs(session_id, question, answer, "llama-3.3-70b-versatile")
print(f"Human: {question}")
print(f"AI: {answer}\n")

"""Fast api code"""

!pip install pyngrok nest-asyncio fastapi uvicorn
from fastapi import FastAPI, UploadFile, File
from pydantic import BaseModel
import uvicorn
import nest_asyncio
from pyngrok import ngrok
import shutil
import uuid

from pyngrok import ngrok
ngrok.set_auth_token("NGROK_AUTH_TOKEN")

app = FastAPI()

class ChatRequest(BaseModel):
    session_id: str
    question: str

@app.get("/")
def home():
    return {"message": "RAG Chatbot is Running! 🚀"}

@app.post("/upload")
async def upload_file(file: UploadFile = File(...)):
    os.makedirs("/content/docs", exist_ok=True)
    file_path = f"/content/docs/{file.filename}"
    with open(file_path, "wb") as f:
        shutil.copyfileobj(file.file, f)

    documents = load_documents("/content/docs")
    splits = text_splitter.split_documents(documents)

    global vectorstore, retriever, history_aware_retriever, rag_chain

    # ✅ Rebuild vectorstore
    vectorstore = Chroma.from_documents(
        documents=splits,
        embedding=embedding_function
    )
    retriever = vectorstore.as_retriever(search_kwargs={"k": 2})

    # ✅ Rebuild history_aware_retriever
    history_aware_retriever = create_history_aware_retriever(
        llm, retriever, contextualize_q_prompt
    )

    # ✅ Rebuild rag_chain CORRECTLY
    question_answer_chain = create_stuff_documents_chain(llm, qa_prompt)
    rag_chain = create_retrieval_chain(
        history_aware_retriever, question_answer_chain
    )
    return {"message": f"✅ {file.filename} uploaded!"}

@app.post("/chat")
def chat(request: ChatRequest):
    try:
        # Step 1 - Get history
        raw_history = get_chat_history(request.session_id)
        chat_history = []
        for msg in raw_history:
            if msg["role"] == "human":
                chat_history.append(HumanMessage(content=msg["content"]))
            elif msg["role"] == "ai":
                chat_history.append(AIMessage(content=msg["content"]))

        # Step 2 - Get answer
        result = rag_chain.invoke({
            "input": request.question,
            "chat_history": chat_history
        })

        # Step 3 - Extract answer safely
        answer = result.get("answer", "No answer found")  # ← SAFE!

        # Step 4 - Save logs
        insert_application_logs(
            request.session_id,
            request.question,
            answer,
            "llama-3.3-70b-versatile"
        )

        return {
            "session_id": request.session_id,
            "question": request.question,
            "answer": answer
        }

    except Exception as e:
        print(f"❌ REAL ERROR: {str(e)}")  # ← Shows in Colab!
        return {"answer": f"Error: {str(e)}"}
@app.get("/new-session")
def new_session():
    session_id = str(uuid.uuid4())
    return {"session_id": session_id}

nest_asyncio.apply()

public_url = ngrok.connect(8000)
print(f"🌍 Your API is LIVE at: {public_url}")

config = uvicorn.Config(app, host="0.0.0.0", port=8000)
server = uvicorn.Server(config)
await server.serve()